### ISSUE TITLE
Clean architecture and TDD

### ISSUE THREAD

**Issue by SimonLab** [dwyl/learn-flutter#15]
Following 
![image](https://user-images.githubusercontent.com/6057298/72339402-0e4f8500-36be-11ea-994b-189196df0424.png)

https://www.youtube.com/watch?v=dc3B_mMrZ-Q&feature=youtu.be

## Lessons

+ [x] **Lesson 1: Explanation & Project Structure - https://www.youtube.com/watch?v=KjE2IDphA_U&list=PLB6lc7nQ1n4iYGE_khpXRdJkJEp9WOech** 

**Time taken: 1 Hour**
 
+ [x] **Lesson 2: Entity,Use Case, Testing (TDD) - https://www.youtube.com/watch?v=lPkWX8xFthE**

**Time taken: 3 Hours**

+ [x] **Lesson 3: Domain Layer Refactoring - https://www.youtube.com/watch?v=Mmq72a0h4jk&list=PLB6lc7nQ1n4iYGE_khpXRdJkJEp9WOech&index=3**

**Time taken: 1 Hour**

+ [x] **Lesson 4: Data Layer Overview & Models - https://www.youtube.com/watch?v=keaTZ9M_U1A&list=PLB6lc7nQ1n4iYGE_khpXRdJkJEp9WOech&index=4**

**Time taken: 2 Hours**

+ [x] **Lesson 5: Data Source Contracts - https://www.youtube.com/watch?v=m_lkZo6CYcs&list=PLB6lc7nQ1n4iYGE_khpXRdJkJEp9WOech&index=5**

**Time taken: 1 Hour**

+ [x] **Lesson 6: Repository Implementation - https://www.youtube.com/watch?v=bfEKPKKy9dA&list=PLB6lc7nQ1n4iYGE_khpXRdJkJEp9WOech&index=6**

**Time taken: 3 Hours**

+ [x] **Lesson 7: Network Information - https://www.youtube.com/watch?v=xWl7GzMDiwg&list=PLB6lc7nQ1n4iYGE_khpXRdJkJEp9WOech&index=7**

**Time taken: 1 Hour**

+ [x] **Lesson 8: Local Data Source - https://www.youtube.com/watch?v=fCguzcvLka8&list=PLB6lc7nQ1n4iYGE_khpXRdJkJEp9WOech&index=8**

**Time taken: 2 Hours**

+ [x] **Lesson 9: Remote Data Source - https://www.youtube.com/watch?v=msGsYPtZnhU&list=PLB6lc7nQ1n4iYGE_khpXRdJkJEp9WOech&index=9**

**Time taken: 2 Hours**

+ [x] **Lesson 10: Bloc Scaffolding & Input Conversion - https://www.youtube.com/watch?v=Ulk9qUErIa4&list=PLB6lc7nQ1n4iYGE_khpXRdJkJEp9WOech&index=10**

**Time taken: 1 Hour**

+ [x] **Lesson 11: Bloc Implementation 1/2 - https://www.youtube.com/watch?v=a8f_qpVHa3w&list=PLB6lc7nQ1n4iYGE_khpXRdJkJEp9WOech&index=11**

**Time taken: 2 Hours**

+ [x] **Lesson 12:  Bloc Implementation 2/2 - https://www.youtube.com/watch?v=YSNeS5S5Nqw&list=PLB6lc7nQ1n4iYGE_khpXRdJkJEp9WOech&index=12**

**Time taken: 2 Hours**

+ [x] **Lesson 13: Dependency Injection - https://www.youtube.com/watch?v=gfLb4rqzio4&list=PLB6lc7nQ1n4iYGE_khpXRdJkJEp9WOech&index=13**

**Time taken: 2 Hours**

+ [x] **Lesson 14: User Interface - https://www.youtube.com/watch?v=G-R-1rzR3zw&list=PLB6lc7nQ1n4iYGE_khpXRdJkJEp9WOech&index=14**

**Time taken: 3 Hours**

**Comment by SimonLab** [comment]
- The architecture is based on 3 layers: Presentation, Domain and Data
- Features have their own folder in `lib/features` and each features have the 3 folders matching the layers :arrow_up: 
![image](https://user-images.githubusercontent.com/6057298/72344757-efef8680-36c9-11ea-87ff-cb735d512592.png)
- The `lib/core` folder contains code that are not attached to a specific feature

**Comment by SimonLab** [comment]
I'm still following the tutorial and arrived at the TDD part. Some part of the code are a bit unclear as I'm not familiar with Dart, for example I blocked a few times on an error when a `;`was missing at the end of line!
I'll try to go over the tutorial completely to have a first understanding of the concepts but I think I will need to go deeper with Dart just after that
- https://exercism.io/my/tracks/dart
- https://dart.dev/guides/language/language-tour

**Comment by iteles** [comment]
Oh, semicolons are back! Man, I didn't miss those in Elm and Elixir 😆

**Comment by SimonLab** [comment]
The clean architecture used on the tutorial:
[![image](https://user-images.githubusercontent.com/6057298/72385304-1ab3fc00-3717-11ea-9961-8c6f053da8b6.png)](https://www.goodreads.com/book/show/18043011-clean-architecture)

- https://pusher.com/tutorials/clean-architecture-introduction

**Comment by SimonLab** [comment]
to read: 
[![image](https://user-images.githubusercontent.com/6057298/72610217-b9f71000-391e-11ea-82dc-d594507da408.png)](https://twitter.com/ThePracticalDev/status/1218133442774347778)

https://dev.to/jeastham1993/clean-architecture-in-net-core-56gh

**Comment by nelsonic** [comment]
@miguelmartins17 can you please add some of this detail (images and explanation) to your notes on the video of TDD and clean architecture? (Thanks!)

**Comment by miguelmartins17** [comment]
@nelsonic What should I put on those who are already made?

**Comment by nelsonic** [comment]
@miguelmartins17 the notes in #36 are _good_.  But you could add the intro including a brief explanation of "Clean Architecture" as I commented in https://github.com/dwyl/learn-flutter/pull/36/files#r380086080

**Comment by miguelmartins17** [comment]
@iteles @nelsonic I'm sorry to interrupt your work, is this the structure I should follow?

![Screen Shot 2020-02-17 at 11 40 30](https://user-images.githubusercontent.com/27420533/74653051-5101f280-517f-11ea-9d07-6e1db9b15944.png)

**Comment by nelsonic** [comment]
@miguelmartins17 Yeah, adding the video/lessons as checklist items and checking them off as you add the notes is a good approach to keeping track of your progress. 👍

**Comment by nelsonic** [comment]
PR #45 merged. ✅ 
Thanks again @miguelmartins17
