### ISSUE TITLE
Todolist Flutter (Step-By-Step)

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#16]
This Tutorial will show you process of building of a todo-list with Flutter.

Make sure to complete the flutter Installation before you get started. 
Here you have the link to Install flutter:
(https://flutter.dev/docs/get-started/install)
 
1-Create a new Flutter Project.

![3fSwulrV0S](https://user-images.githubusercontent.com/27420533/72349907-5037f580-36d5-11ea-8bc8-3f2ec65a28be.png)

2-Delete all the "main.dart" comments that are generated after creating a new project.

**Comment by nelsonic** [comment]
@miguelmartins17 please add your tutorial instructions and code to: 
https://github.com/dwyl/flutter-todo-list-tutorial
