### ISSUE TITLE
command not found: Flutter 

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#27]
In order to access Flutter through the command line and need to change the path of the Flutter folder, I did so but Flutter is still not recognized. 

Is there any way I could have just temporarily changed the path of Flutter?

**Comment by nelsonic** [comment]
@miguelmartins17 what Operating System are you using?
When you open an issue requesting help from the community, always give as _much_ information as possible.

There are a range of options for solving this obstacle:
https://stackoverflow.com/questions/50652071/flutter-command-not-found

The way I aliased the `flutter` command on **Mac** was by editing my `~/.bash_profile` file:
```sh
vi ~/.bash_profile
```
Then add the lines:
```sh
alias flutter="/Users/n/development/flutter/bin/flutter"
```
After you _save_ the file (_e.g: by typing `[esc] :wq` in Vim_)
run the "source" command to load the aliases into your current terminal session:
```sh
source ~/.bash_profile
```
Now the `flutter` command works in terminal e.g: `flutter doctor`, `flutter test` and `flutter run` ✅

**Comment by miguelmartins17** [comment]
@nelsonic I'm using Mac, I'll try to use those commands. Thanks, Nelson. 👍

**Comment by miguelmartins17** [comment]
Even after changing the **path of Flutter** and even editing the **_bash_profile_** when I close the terminal and reopen **Flutter** is no longer recognized. 😕

**Comment by nelsonic** [comment]
@miguelmartins17 the file name and location/path is important. 
Please run the following commands:
```
cat ~/.bash_profile | pbcopy
```
Then _paste_ what you just copied into your next comment. e.g:
```sh
alias AndroidStudio="open -a /Applications/Android\ Studio.app"
alias as="open -a /Applications/Android\ Studio.app"
alias flutter="/Users/n/development/flutter/bin/flutter"
```

**Comment by miguelmartins17** [comment]
@nelsonic I've already been able to access Flutter from the terminal and I've closed it and opened it again and it works.

I went to the documents and changed bash_profile right through the file, and now it works.
Thanks a lot

**Comment by miguelmartins17** [comment]
Can we close this issue now?

**Comment by nelsonic** [comment]
@miguelmartins17 we need to add it to a "troubleshooting" section of the `README.md` 
Similar to how we have in: [setup-instructions.md#trouble-shooting-if-it-doesnt-work](https://github.com/dwyl/learn-heroku/blob/3d976747c6f4e4d2054329ec4e2a5e4116d107b3/SSL-certificate-step-by-step-setup-instructions.md#trouble-shooting-if-it-doesnt-work)

That way _other_ people in the community/team can understand how to fix the problem when they see it.

**Comment by Tharun445** [comment]
even I have the same problem..
Tharuns-MacBook-Pro:~ tharun$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tharun/Documents/\ Development /flutter/bin
Tharuns-MacBook-Pro:~ tharun$ which flutter
Tharuns-MacBook-Pro:~ tharun$ flutter --version
-bash: flutter: command not found

**Comment by flutterq** [comment]
all possible working solution added [[Solved] zsh: command not found: flutter](https://fluttercorner.com/zsh-command-not-found-flutter/)

**Comment by Standaa** [comment]
@nelsonic I am really curious why you would need an alias for this?
In my case I tried adding each of the following to my `.zshrc`:

```
export PATH=$PATH:$HOME:/Dev/flutter/bin
export PATH=/Users/standaa/Dev/flutter/bin:$PATH
export PATH=$PATH:/Users/standaa/Dev/flutter/bin
export PATH="$PATH:$HOME:/Dev/flutter/bin"
export PATH="/Users/standaa/Dev/flutter/bin:$PATH"
export PATH="$PATH:/Users/standaa/Dev/flutter/bin"
```

None of them work. I reloaded the shell each time, restarted iTerm, restarted my laptop and reinstalled the sdk to no avail.

I did the same thing then, pointing to the executables in the `bin`  folder. It did not work either.
All my other paths work fine and I followed the official docs.
