### ISSUE TITLE
When can you really say that an app is reactive?

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#28]
While I'm working trying to summarize the most important parts of this video, I noticed that it's mentioned that Flutter builds Reactive applications, when you can say that an application is reactive ?

https://www.youtube.com/watch?v=n_5JULTrstU&feature=youtu.be

**Comment by nelsonic** [comment]
https://en.wikipedia.org/wiki/Reactive_user_interface

**Comment by miguelmartins17** [comment]
So any interaction the user makes with the application makes the application a reactive application ? 💭

**Comment by nelsonic** [comment]
Indeed. it's just a fancy way of saying that the UI reacts to user interaction.
But it's worth understanding flutter as "reactive" as in _reactive programming_: https://en.wikipedia.org/wiki/Reactive_programming
Flutter is a _declarative_ UI framework which just means you _describe_ the whole layout in the code.
Read: https://stackoverflow.com/questions/1784664/difference-between-declarative-and-imperative

**Comment by miguelmartins17** [comment]
So in a few words I understood the purpose of each of the language types. 👍 

![Screen Shot 2020-02-09 at 12 32 28](https://user-images.githubusercontent.com/27420533/74102101-54223080-4b38-11ea-9213-7b0b1a150fe0.png)

**Comment by nelsonic** [comment]
Yeah, that's a good summary. 💡

**Comment by miguelmartins17** [comment]
@nelsonic Do you think we can close this issue now that the answer has been given?
