### ISSUE TITLE
How can I make a connection between two repositorys

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#30]
How can I make a connection to show the same content in both repositorys?

**Comment by nelsonic** [comment]
@miguelmartins17 I don't think that is possible using Markdown. 🤷‍♂ 
What specific content are you think of mirroring in two repos?

**Comment by miguelmartins17** [comment]
Some information on the articles I am summarizing makes sense in both repositories.
For example in Dart Testing it talks about Flutter Testing

**Comment by nelsonic** [comment]
Just advise people to read `learn-dart` _before_ they read `learn-flutter` so they are aware of everything. 🤓

**Comment by miguelmartins17** [comment]
I hadn't even thought about it. Thank you! 😆
