### ISSUE TITLE
What do you think of Udemy's courses?

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#33]
I've been doing some research and discovered some courses at Udemy about Flutter, do you think they are worth it ? 💭

**Comment by nelsonic** [comment]
@miguelmartins17 when you ask this kind of question, would you mind being _specific_ 
e.g:  https://github.com/dwyl/video/issues/53#issuecomment-445489684

**Comment by miguelmartins17** [comment]
@nelsonic It was a general question, I've had colleagues who bought courses from Udemy and learned a lot but I never used any. Probably the answer will be that there are good courses and courses that waste our time and money.

**Comment by nelsonic** [comment]
The biggest issue I have with Udemy is that they are a _dishonest_ platform. https://youtu.be/NobQXZxjIvs
The individual instructors and courses can be _great_ but the _platform_ is rotten. 
I _avoid_ Udemy wherever possible and I've managed to learn what I need from _free_ resources.
I have nothing against _other_ people using Udemy, that's up to them.

**Comment by miguelmartins17** [comment]
So their goal and even collect as many people as possible.

**Comment by nelsonic** [comment]
@miguelmartins17 Udemy's goal is to make as much money as possible in the shortest amount of time even if they have to ["Slash-and-burn"](https://en.wikipedia.org/wiki/Slash-and-burn) through the content creators. 

We paid the Davinci Resolve course last year for Edu (linked above). The course material was good.
I wish the content was _free_ on YT and the creator made their money from "monetisation" instead,
but each content creator decides how they want to "sell" their content. 

Again, it's up the _individual_ to decide if the Udemy course they are considering is worth it. 👍 
Hope this answers your _general_ question. 
If you have any further questions on _specific_ courses, please open a new issue.

**Comment by nelsonic** [comment]
@miguelmartins17 did you decide to follow any Udemy course for learning Flutter?
If you did, please share a link to the one you chose so others can be informed.
If you did _not_, please describe _why not_ and then _close_ this issue. 
Thanks. 👍

**Comment by miguelmartins17** [comment]
I decided to follow this one:
https://www.udemy.com/course/curso-completo-flutter-app-android-ios/
I think this can help me learn a lot faster and develop my skills

**Comment by nelsonic** [comment]
Cool. Let us know how it goes and what you learned. 
Ideally _summarise_ what you learned so others can also learn what you know.
