### ISSUE TITLE
API Request

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#34]
Later this **_afternoon_** I'll look at Issue #6  so I can help more.

![Screen Shot 2020-02-13 at 10 33 35](https://user-images.githubusercontent.com/27420533/74425960-6e1b8600-4e4c-11ea-89ff-39f8d9425801.png)

**Comment by nelsonic** [comment]
@miguelmartins17 remember you don't need to open a _new_ issue to work on this _existing_ issue #6 ... 💭

**Comment by miguelmartins17** [comment]
@nelsonic I'm sorry, I just thought it would be the best way.
Can I close this issue then?

**Comment by nelsonic** [comment]
@miguelmartins17 there is already a _lot_ of context and checklist (requirements_) in the issue I opened ... 
so yes. Use and comment on the _existing_ issue. 👍
