### ISSUE TITLE
Giphy Invalid authentication credentials

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#37]
Still getting the same error , even after changing the API key.
Trying to understand how can I get the credentials right.

![Screen Shot 2020-02-13 at 20 55 49](https://user-images.githubusercontent.com/27420533/74551796-c8e7d700-4f4b-11ea-9c28-e5824c78d1ff.png)

**Comment by nelsonic** [comment]
@miguelmartins17 this is how I would record this issue:

**Giphy error**
```dart
An error occurred.
GiphyClientError{statusCode: 403, 
exception: {"message":invalid authentication credentials"}
}
```
That way _other_ people facing this issue will _find_ this issue when they Google
and they will also discover your (_eventual_) _solution_ to the problem.

**Comment by miguelmartins17** [comment]
@nelsonic I've tried to find the solution to this mistake, but all the solutions none of them happened with Flutter.

**Comment by nelsonic** [comment]
@miguelmartins17 keep sharing comments for what you are trying. [youtu.be/yKYK1xt-kKo](https://youtu.be/yKYK1xt-kKo?t=43)
Remember to `git push` the _code_ you have written to GitHub so that others can _help_ you debug.
We have _many_ examples of "debugging threads" on GitHub e.g: https://github.com/dwyl/learn-devops/issues/19
Each comment shows the step the person has taken while attempting to solve a challenge. 
`No comments == No effort`

**Comment by miguelmartins17** [comment]
@nelsonic I'm trying to see if the problem was the API key so I went to https://developers.giphy.com/ to get a new one and try again.

**Comment by miguelmartins17** [comment]
So apparently the problem wasn't with the API key.

**Comment by nelsonic** [comment]
And ... what _was_ the problem?
The suspense is killing me. 
![suspense](https://media.giphy.com/media/DUuyU3KyYGLNS/giphy.gif)

**Comment by miguelmartins17** [comment]
@nelsonic I haven't figured it out yet to show images of but to show the gif not.
I've been looking at these two articles but I can't find a solution.

For the gif animations: https://pub.dev/packages/gif_ani#-readme-tab-

https://pub.dev/packages/giphy_picker

**Comment by nelsonic** [comment]
Cool. keep going. you're _almost_ there. 👨‍💻

**Comment by miguelmartins17** [comment]
@nelsonic This is complex. 😕

**Comment by kennethbrent** [comment]
I don't know if this will help anyone else but I was getting the same response from giphy 

`Object {
  "message": "Invalid authentication credentials",
}`

After almost breaking my computer i realized I did not  add an ampersand after my API key before i declared the next URL parameter. 

This works
` const BASE_URL = 'http://api.giphy.com/v1/gifs/search';
  const resJson = await fetch(`${BASE_URL}?api_key=${API_KEY}**&**q=${this.state.search}&limit=20`
`
This did not and caused the error
 `const BASE_URL = 'http://api.giphy.com/v1/gifs/search';
  const resJson = await fetch(`${BASE_URL}?api_key=${API_KEY}q=${this.state.search}&limit=20`
`

**Comment by nelsonic** [comment]
@kennethbrent thanks for sharing! ☀️
