### ISSUE TITLE
Flutter Extensions Error

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#46]
While I was working on the tutorial notes Visual Studio updated Flutter and now all the extensions have errors, I don't know how to solve this since all the pages have errors in the extensions.

![Screen Shot 2020-02-27 at 11 14 58](https://user-images.githubusercontent.com/27420533/75440513-d5106300-5953-11ea-9acd-0a0abb728ca7.png)

![Screen Shot 2020-02-27 at 11 24 46](https://user-images.githubusercontent.com/27420533/75440520-d8a3ea00-5953-11ea-975c-0117b8768938.png)

![Screen Shot 2020-02-27 at 11 23 52](https://user-images.githubusercontent.com/27420533/75440525-db064400-5953-11ea-8e7b-d494b9eb7972.png)

**Comment by miguelmartins17** [comment]
@nelsonic One more update this time on the extensions package, I hope it helps.

![Screen Shot 2020-02-28 at 09 02 05](https://user-images.githubusercontent.com/27420533/75526218-40683c80-5a09-11ea-96c6-dbeb230e0f12.png)

**Comment by nelsonic** [comment]
@miguelmartins17 whenever you are faced with upgrades, you should log the version you _currently_ have on your machine and the new version you are upgrading to (_in a GitHub comment_). 
That will help you narrow the search when things do go according to plan.

**Comment by miguelmartins17** [comment]
This is the error that appears to me, so I searched for that same error in stackoverflow and this page appeared to me that could be useful for my problem.

https://stackoverflow.com/questions/53756164/missing-concrete-implementation-of-getter-and-setter

**Comment by miguelmartins17** [comment]
How does Override interact with the created methods?

**Comment by miguelmartins17** [comment]
https://stackoverflow.com/questions/30274107/how-can-a-missing-concrete-implementation-warning-be-suppressed

**Comment by miguelmartins17** [comment]
I've already got three, the others are missing.

![Screen Shot 2020-02-28 at 10 35 10](https://user-images.githubusercontent.com/27420533/75541565-1ec18200-5a16-11ea-9f0a-3b45491551fa.png)

**Comment by nelsonic** [comment]
@miguelmartins17 looks like good progress. 👍 
it's _really_ good that you are facing these challenges now.
Sadly when you are building things in the real world, there is no complete manual with all the steps and new hurdles will always appear. Practicing solving challenges you haven't seen before is _essential_. 👍

**Comment by miguelmartins17** [comment]
@nelsonic Today I've been working on trying to get all the tests back through without mistakes, I've already got some but there are still others missing.




![Screen Shot 2020-02-29 at 20 19 54](https://user-images.githubusercontent.com/27420533/75614479-05612880-5b31-11ea-8a91-272972a5cd84.png)

**Comment by nelsonic** [comment]
@miguelmartins17 cool. This might feel tedious, but it is _very_ valuable experience! Updating/maintaining code is one of the biggest jobs in software. People who expect it to be only _building_ new features are always _surprised_. Having to _fix_ code when it "breaks" teaches us to write simpler more maintainable code. 💭

**Comment by miguelmartins17** [comment]
@miguelmartins17 I don't think I can use `nosuchmethod( )` here because it takes away the function that was supposed to be doing the code.

![Screen Shot 2020-03-01 at 11 56 17](https://user-images.githubusercontent.com/27420533/75625218-e5bf1400-5bb3-11ea-9fb7-f564764d4e9a.png)

**Comment by miguelmartins17** [comment]
@nelsonic NoSuchMethod always indicates wrong loading of classes or versions.

So it means that right away I must have an error and since I tried to use NoSuchMethod to fix it got even worse what I'm going to do is delete NoSuchMethod and search for the error solution in Google.

**Comment by nelsonic** [comment]
Good plan. That sounds like a more sane approach. 👍

**Comment by miguelmartins17** [comment]
@nelsonic One of the solutions you could use and through the quick fix of Visual Studio.
One of the options is to write the override that is not present.
I've been writing and now almost all the tests pass, except three of them.


![Screen Shot 2020-03-02 at 16 56 59](https://user-images.githubusercontent.com/27420533/75698580-de2c6780-5ca6-11ea-991a-381bd468516c.png)
