### ISSUE TITLE
How do I pass files from an Android to a Mac?

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#49]
I needed to pass some screenshots of my Android to the Mac do I need some program to do it?

**Comment by nelsonic** [comment]
@miguelmartins17 the easiest option is to use Google Photos or email the files to yourself. ☁️ 
We've used Android File Transfer https://www.android.com/filetransfer/ in the past; it works OK. 💡

**Comment by miguelmartins17** [comment]
@nelsonic Thanks, I sent the screenshots by email.
So I can put them there now. 😄

**Comment by iteles** [comment]
@miguelmartins17 Please close this issue if you've managed to do this already as I don't think it is relevant to this particular repo on the whole (so no need to keep it open).

**Comment by miguelmartins17** [comment]
Yes, thank you very much I have solved the problem.
