### ISSUE TITLE
Chore: How to run the `learn-flutter/demo_app`? 🤷‍♂️ 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-flutter#75]
At present the [`/demo_app`](https://github.com/dwyl/learn-flutter/tree/9f684aaa8e6b72dc80c8e6dfb76836928c6966a4/demo_app) is just a directory without any helpful info:

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/194400/215450558-6a04efe8-51ff-40c6-8a38-63589700df12.png">

This super unhelpful to someone who is **`new`** to `Flutter`.
It forces them to go searching for how to run the app.

In the [`/README.md`](https://github.com/dwyl/learn-flutter/tree/9f684aaa8e6b72dc80c8e6dfb76836928c6966a4) there is no instance of a `git clone` instruction:

<img width="1428" alt="learn-flutter-readme-no-git-clone" src="https://user-images.githubusercontent.com/194400/215451228-388148ac-cc55-4390-bb26-e8831770d0cc.png">

So the `demo_app` is an "island" that nobody knows how to reach. 
Worse it's decaying code that will "[rot](https://en.wikipedia.org/wiki/Software_rot)" over time because nobody will update it. 😢 

# Todo

We need to:

+ [ ] fix this oversight and _integrate_ the `demo_app` into the main `README.md` 
***or*** create a `new` `README.md` inside `/demo_app` so that people at least know how to run it. 💭

**Comment by nelsonic** [comment]
If we are going to place a _large_ bet on using `Flutter` for our `App`, this is _unacceptable_. 
In it's current state I would grade this tutorial a **`C-`**, passable, but not great.
It needs to be an **`A+`** and a reference that _anyone_ can use to learn `Flutter` as fast as possible.

**Comment by nelsonic** [comment]
_Obviously_ it's _my_ fault for not giving enough feedback on the PR: https://github.com/dwyl/learn-flutter/pull/69
But I ran out of steam on reviewing it. There was just "too much" that needed to be done... 😖 
So I'm picking off this small piece of it now.

**Comment by nelsonic** [comment]
Watching: 
Flutter Tutorial - How To Run App On Android Emulator & Run App On Android Device [2021]: https://youtu.be/QjgmTiD8prA

[![yt](https://user-images.githubusercontent.com/194400/215456253-8fdf8b65-4cde-46b0-b365-c343c12bf790.png)](https://youtu.be/QjgmTiD8prA)

**Comment by nelsonic** [comment]
This is an example of an _unconstrained_ and non-highlighted screenshot:

<img width="3008" alt="android-studio-device-manager" src="https://user-images.githubusercontent.com/194400/215464262-f6074592-fa2e-4162-87eb-8979272347bf.png">

It requires a lot more effort for the _reader_ to read and understand what they are looking for in the image.

By contrast, this is a constrained and annotated screenshot:

\<img width="193" alt="android-studio-device-manager-constrained-annotated-small" src="https://user-images.githubusercontent.com/194400/215464933-de8c0a60-883b-466f-8591-964c42ff736b.png">

But ... the screenshot was captured on a `4k` Display so it's _tiny_ 🔍 
So the Engineer who want's to make **`A+`** docs will go the _extra_ mile and Google:
https://www.google.com/search?q=android+studio+change+size+interface
Answer: https://stackoverflow.com/questions/45124698/change-ui-font-size-in-android-studio

Before:
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/194400/215465573-bfe75e36-1427-4d60-a4d8-c1e508bfaede.png">

After:
<img width="1094" alt="android-studio-change-button-size" src="https://user-images.githubusercontent.com/194400/215465762-38b14ff9-6394-4bc2-8098-0f5e82a7d33f.png">

This results in the interface in my `Android Studio` being considerably larger so the screenshot is clearer:

<img width="195" alt="android-studio-device-manager-larger" src="https://user-images.githubusercontent.com/194400/215466189-3cf1d09c-8379-4d43-ae8a-563dfd9c7ec2.png">

Yes, this takes an extra _minute_ for the person writing the docs. 
But it saves 10 seconds `forEach` person ***reading*** the doc. 
So as an org, we only need 6 people to read the _clearer_ doc to have a net positive effect.
And since we _know_ that our docs are read by ***thousands*** of people. 
We want to ***always*** make the **_extra_ effort** to make everything as clear as possible.
This is what **`A+`** looks like. 

How You Do Anything Is How You Do Everything ... 
https://medium.com/thrive-global/how-you-do-anything-is-how-you-do-everything-bc6e264e40ee

**Comment by nelsonic** [comment]
In `Android Studio` I have the `demo_app/lib/main.dart` running in the `Pixel 6` Simulator:
<img width="1841" alt="image" src="https://user-images.githubusercontent.com/194400/215604481-a11fe663-f5d1-487a-977f-d1ff840b6381.png">

At the top of `Android Studio` I see the following message: 
"Dart SDK is not configured"
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/194400/215604583-70667d89-080f-49ba-a39e-8f0cb8041402.png">

If you click on the "Download Dart SDK" it will open a Web Page:
https://dart.dev/get-dart
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/194400/215604851-29f09ebe-85d5-4414-90f6-b28645dca50c.png">

Ran the suggested commands:
```sh
brew tap dart-lang/dart
brew install dart
brew info dart
```

Got:

```sh
==> dart-lang/dart/dart: stable 2.19.0, HEAD
SDK
https://dart.dev
Conflicts with:
  dart-beta (because dart-beta ships the same binaries)
/opt/homebrew/Cellar/dart/2.19.0 (1,039 files, 612.5MB)
  Built from source on 2023-01-30 at 22:00:31
From: https://github.com/dart-lang/homebrew-dart/blob/HEAD/Formula/dart.rb
==> Options
--HEAD
	Install HEAD version
==> Caveats
Please note the path to the Dart SDK:
  /opt/homebrew/opt/dart/libexec
```

Attempted to run:
```sh
brew upgrade dart
```

Got: 
```sh
Warning: dart-lang/dart/dart 2.19.0 already installed
```

So already have the latest version, at least according to the `Brew` cask.

But in `Android Studio` I still see the error:
"Error: a path to Dart SDK is not specified.":

<img width="1315" alt="error-path-to-dart-SDK-is-not-specified" src="https://user-images.githubusercontent.com/194400/215607434-02314dbe-37a6-4562-a65c-27b2fc41febc.png">

Read: https://stackoverflow.com/questions/48650831/dart-sdk-is-not-configured

Ran
```sh
flutter doctor -v
```

Shows:
```sh
/opt/homebrew/Caskroom/flutter/3.3.8/flutter
```

So ...

```sh
/opt/homebrew/Caskroom/flutter/3.3.8/flutter/bin/cache/dart-sdk
```

Open preferences: <kbd>⌘</kbd>+<kbd>,</kbd>
Open `Dart` settings and paste this path into the path field:

<img width="1315" alt="dart-sdk-apply-ok" src="https://user-images.githubusercontent.com/194400/215608986-59725641-8e86-4ef2-8ed2-70f29d0ef6d1.png">

**Comment by nelsonic** [comment]
```sh
cd learn-flutter/demo_app
```

```sh
flutter packages get
```

Meanwhile, followed instructions in: https://docs.flutter.dev/get-started/test-drive

and got the `demo_app` (Todo List) running in the iOS iPhone SE Sim:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/194400/215612874-1f643bd7-063e-4965-b8df-b564ed51e57f.png">

**Comment by nelsonic** [comment]
https://github.com/dwyl/learn-flutter/blob/9f684aaa8e6b72dc80c8e6dfb76836928c6966a4/demo_app/lib/repository/todoRepository.dart#L16
Loads data from: https://jsonplaceholder.typicode.com/todos

<img width="839" alt="image" src="https://user-images.githubusercontent.com/194400/215614744-2638471a-963d-4bf0-8bc9-ffd06ddad04b.png">

Dunno _why_ this needs to load remote data and not allow addition of any new Todos. 
But at least it works. ✅

**Comment by LuchoTurtle** [comment]
This should be marked as "done", since #74 has already been merged, in my opinion.

**Comment by nelsonic** [comment]
Thanks for tidying up @LuchoTurtle 👌
